apiVersion: v1
kind: Pod
metadata:
  labels:
    run: loop
  name: loop
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do for i in $(seq 1 5); do echo "$i - A piece of cake !"; done;
      sleep 5; done
    image: busybox:1.36.1
    name: loop
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
