apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-dev
  namespace: ns-dev
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
status: {}
