apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-prod
  namespace: ns-prod
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    requests.cpu: "2"
    requests.memory: 2Gi
status: {}
